"""Interactive `.env` scaffolding for `matrioska init`.

Prompts the user for provider, model, and API key, detects existing
`.env`, and writes a Matrioska-ready environment file. Optionally
seeds `MATRIOSKA.md` with project conventions.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Provider catalog: (id, display name, default base_url, suggested model, key_hint)
_PROVIDERS: List[Tuple[str, str, str, str, str]] = [
    ("openai",     "OpenAI",          "https://api.openai.com/v1",            "gpt-4o-mini",                 "sk-..."),
    ("anthropic",  "Anthropic",       "https://api.anthropic.com",            "claude-sonnet-4",             "sk-ant-..."),
    ("groq",       "Groq",            "https://api.groq.com/openai/v1",       "llama-3.3-70b-versatile",     "gsk_..."),
    ("openrouter", "OpenRouter",      "https://openrouter.ai/api/v1",         "anthropic/claude-sonnet-4",   "sk-or-..."),
    ("deepseek",   "DeepSeek",        "https://api.deepseek.com/v1",          "deepseek-chat",               "ds_..."),
    ("xai",        "xAI (Grok)",      "https://api.x.ai/v1",                  "grok-2-latest",               "xai-..."),
    ("mistral",    "Mistral",         "https://api.mistral.ai/v1",            "mistral-large-latest",        "..."),
    ("together",   "Together",        "https://api.together.xyz/v1",          "Qwen/Qwen2.5-Coder-32B-Instruct", "..."),
    ("nvidia",     "NVIDIA NIM",      "https://integrate.api.nvidia.com/v1",  "meta/llama-3.1-70b-instruct", "nvapi-..."),
    ("ollama",     "Ollama (local)",  "http://localhost:11434/v1",            "llama3.1:8b",                 "ollama"),
]


def _ask(prompt: str, default: str = "") -> str:
    """Prompt the user, returning the input (or default if blank)."""
    suffix = f" [{default}]" if default else ""
    try:
        ans = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        return default
    return ans or default


def _ask_choice(prompt: str, choices: List[str], default_idx: int = 0) -> int:
    """Numeric multiple-choice prompt. Returns the chosen index."""
    print(prompt)
    for i, label in enumerate(choices, 1):
        marker = "*" if i - 1 == default_idx else " "
        print(f"  {marker} {i}) {label}")
    while True:
        raw = _ask("Choose", default=str(default_idx + 1))
        if not raw.isdigit():
            print("  → please enter a number")
            continue
        n = int(raw)
        if 1 <= n <= len(choices):
            return n - 1
        print(f"  → out of range (1–{len(choices)})")


def _ask_yes_no(prompt: str, default: bool = True) -> bool:
    suffix = "Y/n" if default else "y/N"
    raw = _ask(f"{prompt} ({suffix})", default="Y" if default else "N").lower()
    return raw.startswith("y") if raw else default


def _read_existing(env_path: Path) -> Dict[str, str]:
    out: Dict[str, str] = {}
    if not env_path.exists():
        return out
    for raw in env_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _render_env(values: Dict[str, str]) -> str:
    """Render the .env file with grouped sections + comments."""
    sections = [
        ("Provider", ["MATRIOSKA_PROVIDER", "MATRIOSKA_BASE_URL",
                       "MATRIOSKA_API_KEY", "MATRIOSKA_API_KEYS", "MATRIOSKA_EXTRA_ENDPOINTS"]),
        ("Models", ["MATRIOSKA_MODEL", "MATRIOSKA_ARCHITECT_MODEL",
                    "MATRIOSKA_GENERATOR_MODEL", "MATRIOSKA_VALIDATOR_MODEL",
                    "MATRIOSKA_JUDGE_MODEL", "MATRIOSKA_REPAIRER_MODEL"]),
        ("Pipeline", ["MATRIOSKA_MAX_REPAIRS", "MATRIOSKA_MAX_DEPTH",
                      "MATRIOSKA_PARALLEL", "MATRIOSKA_ARCHITECT_CANDIDATES"]),
        ("Phases", ["MATRIOSKA_ENABLE_TOT", "MATRIOSKA_ENABLE_REFLEXION",
                    "MATRIOSKA_ENABLE_TEST_DESIGN", "MATRIOSKA_USE_ACI_REPAIR",
                    "MATRIOSKA_ENABLE_SANDBOX"]),
        ("Vault & misc", ["MATRIOSKA_ENABLE_VAULT", "MATRIOSKA_VAULT_DIR",
                          "MATRIOSKA_LOG_LEVEL"]),
    ]
    lines = [
        "# Generated by `matrioska init`",
        "# Edit freely — every key can also be overridden via CLI flag.",
        "",
    ]
    written = set()
    for title, keys in sections:
        block: List[str] = []
        for k in keys:
            if k in values and values[k] != "":
                block.append(f'{k}={values[k]}')
                written.add(k)
        if block:
            lines.append(f"# ── {title} ─────────────────────────────────────────")
            lines.extend(block)
            lines.append("")
    # Spill remaining keys
    leftovers = [k for k in values if k not in written and values[k] != ""]
    if leftovers:
        lines.append("# ── Other ──────────────────────────────────────────────")
        for k in leftovers:
            lines.append(f'{k}={values[k]}')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_MATRIOSKA_MD_TEMPLATE = """# {project_name}

## Project conventions

Notes injected into the Architect on every run. Edit freely.

### Stack
- Language: Python 3.11+
- Frameworks: <add yours>
- Storage: <add yours>

### Style
- Prefer small, focused modules
- Avoid unnecessary abstractions until 3rd repetition
- Type hints on public functions; docstrings only when the why is non-obvious

### Don'ts
- No global mutable state
- No silent exception swallowing

### Notes for the agent
- <add domain notes or constraints here>
"""


def run_init(cwd: Optional[Path] = None) -> int:
    """Interactive `.env` scaffolder. Returns process exit code."""
    cwd = cwd or Path.cwd()
    env_path = cwd / ".env"

    print("─" * 60)
    print(" Matrioska init")
    print("─" * 60)
    print(f" Target: {env_path}")
    print()

    existing = _read_existing(env_path)
    if existing:
        print(f"Found existing .env with {len(existing)} key(s).")
        action = _ask_choice(
            "What should I do?",
            ["Merge (keep existing values, fill missing)",
             "Overwrite (replace with new values)",
             "Abort"],
            default_idx=0,
        )
        if action == 2:
            print("Aborted.")
            return 0
        merge = action == 0
    else:
        merge = False

    # Provider selection
    labels = [f"{disp} — model: {model}" for _id, disp, _url, model, _hint in _PROVIDERS]
    current_provider = existing.get("MATRIOSKA_PROVIDER", "")
    default_idx = next(
        (i for i, (pid, *_r) in enumerate(_PROVIDERS) if pid == current_provider),
        0,
    )
    idx = _ask_choice("\nPick a provider:", labels, default_idx=default_idx)
    pid, _disp, default_url, default_model, key_hint = _PROVIDERS[idx]

    base_url = _ask(
        "Base URL",
        default=existing.get("MATRIOSKA_BASE_URL") or default_url,
    )

    api_key = ""
    if pid != "ollama":
        api_key_default = existing.get("MATRIOSKA_API_KEY", "")
        prompt_label = "API key" + (f" (hint: {key_hint})" if not api_key_default else " (press Enter to keep current)")
        api_key = _ask(prompt_label, default=api_key_default)
    else:
        api_key = "ollama"

    model = _ask("Default model", default=existing.get("MATRIOSKA_MODEL") or default_model)

    use_role_models = _ask_yes_no("\nSet per-role model overrides? (architect/generator/validator/judge)", default=False)
    arch_model = gen_model = val_model = judge_model = rep_model = ""
    if use_role_models:
        arch_model = _ask("Architect model", default=existing.get("MATRIOSKA_ARCHITECT_MODEL") or model)
        gen_model = _ask("Generator model", default=existing.get("MATRIOSKA_GENERATOR_MODEL") or model)
        val_model = _ask("Validator model", default=existing.get("MATRIOSKA_VALIDATOR_MODEL") or model)
        judge_model = _ask("Judge model", default=existing.get("MATRIOSKA_JUDGE_MODEL") or model)
        rep_model = _ask("Repairer model", default=existing.get("MATRIOSKA_REPAIRER_MODEL") or model)

    multikey = ""
    if _ask_yes_no("\nUse multiple API keys for rotation? (comma-separated)", default=False):
        multikey = _ask("Comma-separated API keys", default=existing.get("MATRIOSKA_API_KEYS", ""))

    # Build values dict (merge-respecting)
    values: Dict[str, str] = dict(existing) if merge else {}
    values.update({
        "MATRIOSKA_PROVIDER": pid,
        "MATRIOSKA_BASE_URL": base_url,
        "MATRIOSKA_API_KEY": api_key,
        "MATRIOSKA_MODEL": model,
    })
    if multikey:
        values["MATRIOSKA_API_KEYS"] = multikey
    if use_role_models:
        values.update({
            "MATRIOSKA_ARCHITECT_MODEL": arch_model,
            "MATRIOSKA_GENERATOR_MODEL": gen_model,
            "MATRIOSKA_VALIDATOR_MODEL": val_model,
            "MATRIOSKA_JUDGE_MODEL": judge_model,
            "MATRIOSKA_REPAIRER_MODEL": rep_model,
        })

    # Write .env
    env_path.write_text(_render_env(values), encoding="utf-8")
    print(f"\n✓ Wrote {env_path}")

    # MATRIOSKA.md scaffold
    md_path = cwd / "MATRIOSKA.md"
    if not md_path.exists():
        if _ask_yes_no("\nCreate MATRIOSKA.md (project conventions injected into the Architect)?", default=True):
            project_name = _ask("Project name", default=cwd.name)
            md_path.write_text(
                _MATRIOSKA_MD_TEMPLATE.format(project_name=project_name),
                encoding="utf-8",
            )
            print(f"✓ Wrote {md_path}")

    print("\nNext steps:")
    print(f"  matrioska run --task \"Create a CLI todo app with SQLite\"")
    print(f"  matrioska run --task '…' --quick   # rapid iteration")
    print(f"  matrioska run --task '…' --mode plan   # plan only")
    return 0
